name: Workflow
on: [push]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: "7.4"
      - name: Change directory to lesson10
        run: cd lesson10
      - name: Install dependecies
        run: composer install
      - name: Install Faker
        run: composer require fzaninotto/faker
      - name: Run chromedriver
        run: nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null/ 2>&1 &
      - name: Run test cases
        run: php vendor/bin/codecept run --steps -vvv --xml
      - name: Junit Report Action
        uses: mikepenz/action-junit-report@2.4.2
        with:
          report_paths: "tests/_output/report.xml"
